DROP TABLE IF EXISTS TB_FUNCIONARIOS;
 
CREATE TABLE TB_FUNCIONARIOS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  primeiro_nome VARCHAR(100) NOT NULL,
  ultimo_nome VARCHAR(100) NOT NULL,
  rg VARCHAR(15) NOT NULL,
  cpf VARCHAR(15) NOT NULL,
  telefone VARCHAR(10) NULL,
  email VARCHAR(100)  NULL
);